frontend/controllers/DashboardController.php
<?php

namespace frontend\controllers;

class DashboardController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $this->layout='dashboard';
        return $this->render('welcome');
    }

}

frontend/controllers/HomeController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\User;

/**
 * Home controller
 */
class HomeController extends Controller
{
    //public $param;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout='home';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return Yii::$app->getResponse()->redirect(Yii::$app->urlManager->createUrl('/dashboard/'));
            
        }
        
        $model_register = new SignupForm();
        if ($model_register->load(Yii::$app->request->post())) {
            if ($user = $model_register->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        Yii::$app->view->params['model_register'] = $model_register;
        Yii::$app->view->params['model'] = $model;
        
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            return Yii::$app->getResponse()->redirect("/dashboard/index");
            //return Yii::$app->getResponse()->redirect(Yii::$app->urlManagerBackEnd->createUrl(''));
            
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
        public function actionAdmin()
    {
        //$this->layout='admin/main';
        return $this->render('admin/welcome');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionVerification($vToken){
        $user = User::findOne(['verification_token' => $vToken, 'status' => User::STATUS_ACTIVE]);
        $user->removeVerificationToken();
        $user->save(false);
        return $this->goHome();
    }
}

frontend/views/layouts/dashboard/chat.php
      <div class="small-chat-box fadeInRight animated">

            <div class="heading" draggable="true">
                <small class="chat-date pull-right">
                    02.19.2015
                </small>
                Small chat
            </div>

            <div class="content">

                <div class="left">
                    <div class="author-name">
                        Monica Jackson <small class="chat-date">
                        10:02 am
                    </small>
                    </div>
                    <div class="chat-message active">
                        Lorem Ipsum is simply dummy text input.
                    </div>

                </div>
                <div class="right">
                    <div class="author-name">
                        Mick Smith
                        <small class="chat-date">
                            11:24 am
                        </small>
                    </div>
                    <div class="chat-message">
                        Lorem Ipsum is simpl.
                    </div>
                </div>
                <div class="left">
                    <div class="author-name">
                        Alice Novak
                        <small class="chat-date">
                            08:45 pm
                        </small>
                    </div>
                    <div class="chat-message active">
                        Check this stock char.
                    </div>
                </div>
                <div class="right">
                    <div class="author-name">
                        Anna Lamson
                        <small class="chat-date">
                            11:24 am
                        </small>
                    </div>
                    <div class="chat-message">
                        The standard chunk of Lorem Ipsum
                    </div>
                </div>
                <div class="left">
                    <div class="author-name">
                        Mick Lane
                        <small class="chat-date">
                            08:45 pm
                        </small>
                    </div>
                    <div class="chat-message active">
                        I belive that. Lorem Ipsum is simply dummy text.
                    </div>
                </div>


            </div>
            <div class="form-chat">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control">
                    <span class="input-group-btn"> <button
                        class="btn btn-primary" type="button">Send
                </button> </span></div>
            </div>

        </div>
        <div id="small-chat">

            <span class="badge badge-warning pull-right">5</span>
            <a class="open-small-chat">
                <i class="fa fa-comments"></i>

            </a>
        </div>

frontend/views/layouts/dashboard/left_side.php
<?php 
use yii\helpers\Html; 
use app\models\Dashleft;
?>
<nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="<?=$baseUrl?>/img/profile_small.jpg" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">
                                        <?php echo Yii::$app->user->identity->username ;?>
                                    </strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="profile.html">Profile</a></li>
                                <li><a href="contacts.html">Contacts</a></li>
                                <li><a href="mailbox.html">Mailbox</a></li>
                                <li class="divider"></li>
                                <li><a>
                                            <?php
                                                echo Html::beginForm(['/home/logout'], 'post')
                                                . Html::submitButton(
                                                    '<i class="font-normal"></i>'.'Log out',
                                                    ['class' => 'btn btn-link logout']
                                                )
                                                . Html::endForm();
                                            ?>
                                </a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li class="active">
                                <a href="index.html"><i class="fa fa-th-large">                            
                            </i> <span class="nav-label">Dashboards</span> 
                            <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li class="active"><a href="index.html">Dashboard v.1</a></li>
                            <li><a href="dashboard_2.html">Dashboard v.2</a></li>
                            <li><a href="dashboard_3.html">Dashboard v.3</a></li>
                            <li><a href="dashboard_4_1.html">Dashboard v.4</a></li>
                            <li><a href="dashboard_5.html">Dashboard v.5 </a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="layouts.html">
                            <i class="fa fa-diamond"></i> 
                            <span class="nav-label">Layouts</span>
                        </a>
                    </li>
                    
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i>
                            
                            <span class="nav-label">Graphs</span>
                            <span class="fa arrow"></span></a>
                            
                        <ul class="nav nav-second-level collapse">
                            <li><a href="graph_flot.html">Flot Charts</a></li>
                            <li><a href="graph_morris.html">Morris.js Charts</a></li>
                            <li><a href="graph_rickshaw.html">Rickshaw Charts</a></li>
                            <li><a href="graph_chartjs.html">Chart.js</a></li>
                            <li><a href="graph_chartist.html">Chartist</a></li>
                            <li><a href="c3.html">c3 charts</a></li>
                            <li><a href="graph_peity.html">Peity Charts</a></li>
                            <li><a href="graph_sparkline.html">Sparkline Charts</a></li>
                        </ul>
                    </li>
                            
                            <?php                            
                            $menu_head = Dashleft::find() ->where(['item_bin' => 1]) ->all();
                            $menu = Dashleft::find()->where(['item_bin' => 0]) ->all();
                            ?>
                            
                            <?php 
                            foreach ($menu_head as $i){ ?>
                            <li>
                                <a href="#"><i class=<?php echo $i['i_class'];?>></i>
                                    <span class=<?php echo $i['span_head'];?>><?php echo $i['content']; ?></span>
                                    <span class="<?php echo $i['sub_span'];?>"></span>
                                </a>                            
                                    <ul class=<?php echo $i['ul_class'];?>>   
                                          <?php                                     
                                         foreach ($menu as $j){ 
                                         if ($i['id'] == $j['span_head_title']){?>
                                         <li><a href=<?php echo $j['href']; ?>><?php echo $j['content'];?></a></li>                                      
                                         <?php } }?> 
                                    </ul> 
                            </li>
                                    <?php }?>                                   
  
                </ul>
            </div>
        </nav>

frontend/views/layouts/dashboard/nav_bar.php
<?php 
use yii\helpers\Html; 

?>
<div id="page-wrapper" class="gray-bg dashbard-1">
<div class="row border-bottom">
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">
<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
<form role="search" class="navbar-form-custom" action="search_results.html">
    <div class="form-group">
            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
    </div>
</form>
</div>
<ul class="nav navbar-top-links navbar-right">
        <li>
                <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
        </li>
        <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                        <li>
                                <div class="dropdown-messages-box">
                                        <a href="profile.html" class="pull-left">
                                                <img alt="image" class="img-circle" src="<?=$baseUrl?>/img/a7.jpg">
                                        </a>
                                        <div class="media-body">
                                                <small class="pull-right">46h ago</small>
                                                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                        </div>
                                </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <div class="dropdown-messages-box">
                                        <a href="profile.html" class="pull-left">
                                                <img alt="image" class="img-circle" src="<?=$baseUrl?>/img/a4.jpg">
                                        </a>
                                        <div class="media-body ">
                                                <small class="pull-right text-navy">5h ago</small>
                                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                        </div>
                                </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <div class="dropdown-messages-box">
                                        <a href="profile.html" class="pull-left">
                                                <img alt="image" class="img-circle" src="<?=$baseUrl?>/img/profile.jpg">
                                        </a>
                                        <div class="media-body ">
                                                <small class="pull-right">23h ago</small>
                                                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                        </div>
                                </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <div class="text-center link-block">
                                        <a href="mailbox.html">
                                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                        </a>
                                </div>
                        </li>
                </ul>
        </li>
        <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                        <li>
                                <a href="mailbox.html">
                                        <div>
                                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                                <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <a href="profile.html">
                                        <div>
                                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                                <span class="pull-right text-muted small">12 minutes ago</span>
                                        </div>
                                </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <a href="grid_options.html">
                                        <div>
                                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                                <span class="pull-right text-muted small">4 minutes ago</span>
                                        </div>
                                </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                                <div class="text-center link-block">
                                        <a href="notifications.html">
                                                <strong>See All Alerts</strong>
                                                <i class="fa fa-angle-right"></i>
                                        </a>
                                </div>
                        </li>
                </ul>
        </li>


        <li>            
            <?php
                echo Html::beginForm(['/home/logout'], 'post')
                . Html::submitButton(
                    '<i class="fa fa-sign-out"></i>'.'Log out', // . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm();
            ?>
        </li>
        <li>
                <a class="right-sidebar-toggle">
                        <i class="fa fa-tasks"></i>
                </a>
        </li>
</ul>

</nav>
</div>
													